CREATE TABLE TEST2
(
    ID        NUMBER(3) PRIMARY KEY,
    PARENT_ID NUMBER,
    CHECK (ID <> PARENT_ID),
    STR       VARCHAR2(255),
    CHECK(INSTR(STR, '99') = 0),
    CONSTRAINT PARENT_ID
        FOREIGN KEY (ID)
        REFERENCES TEST2 (ID)
)
