SELECT *
FROM CONTR
ORDER BY DEPART_ID, AMOUNT DESC;

SELECT c.*,
       END_DATE - BEG_DATE AS DIFFERENCE
FROM CONTR c
WHERE END_DATE IS NOT NULL
UNION
SELECT c.*,
       NULL AS DIFFERENCE
FROM CONTR c
WHERE END_DATE IS NULL
ORDER BY DIFFERENCE;