SELECT depart_id,
       SUM(salary),
       MIN(salary),
       MAX(salary),
       AVG(salary),
       COUNT(pers_id)
FROM pers
GROUP BY DEPART_ID
HAVING COUNT(PERS_ID) > 15;
--HAVING COUNT(PERS_ID) > 20
SELECT d.*,
       COUNT_PERS_ID,
       p.SUM_SALARY,
       p.MIN_SALARY AS FACT_MIN_SALARY,
       p.MAX_SALARY AS FACT_MAX_SALARY,
       p.AVG_SALARY
FROM DEPART d,
     (SELECT DEPART_ID,
             SUM(SALARY)    AS SUM_SALARY,
             MIN(SALARY)    AS MIN_SALARY,
             MAX(SALARY)    AS MAX_SALARY,
             AVG(SALARY)    AS AVG_SALARY,
             COUNT(PERS_ID) AS COUNT_PERS_ID
      FROM PERS
      GROUP BY DEPART_ID
      HAVING COUNT(PERS_ID) > 15) p
WHERE d.DEPART_ID = p.DEPART_ID
  AND NOT p.AVG_SALARY BETWEEN d.MIN_SALARY AND d.MAX_SALARY;